name: macos-latest
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  macos-latest-build:
    uses: ./.github/workflows/ci.yml
    with:
      os: macos-latest
      compiler: llvm
      conan_configure_preset: conan-release
      conan_build_preset: conan-release
      conan_test_preset: conan-release
