name: windows-latest
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  windows-latest-build:
    uses: ./.github/workflows/ci.yml
    with:
      os: windows-latest
      compiler: msvc
      conan_configure_preset: conan-default
      conan_build_preset: conan-release
      conan_test_preset: conan-release
